def execute_llm_select_query(llm_sql_query: str):
    """
    Executes a SQL SELECT query generated by a Large Language Model (LLM) on a Supabase database 
    via a Remote Procedure Call (RPC), while enforcing strict security and processing results 
    into a consistent JSON format.

    Overview
    --------
    This function allows dynamic execution of SQL SELECT queries automatically generated by an 
    LLM based on natural language user input. It provides a secure and standardized mechanism 
    to execute queries against a Supabase database without exposing the system to unsafe SQL statements.

    Workflow
    --------
    1. Security Check:
       - Only SELECT statements are allowed to prevent accidental or malicious data modification.
       - Raises ValueError if the query contains anything other than a SELECT statement.

    2. Database Connection:
       - Establishes a connection to Supabase using the `create_supabase_connection` utility.

    3. Query Preparation:
       - Strips whitespace and removes trailing semicolons to ensure clean execution.

    4. Query Execution:
       - Executes the SQL query via the Supabase RPC function named "execute_sql".
       - RPC typically returns each row as a JSON object, e.g., [{'row_to_json': {...}}] or {...}.

    5. Result Processing:
       - Iterates over the returned rows to extract JSON objects.
       - Handles different formats gracefully:
         - If 'row_to_json' key exists, extracts its value.
         - Otherwise, appends the row directly.
       - Returns a consistent list of JSON records.

    6. Error Handling:
       - Catches exceptions during query execution.
       - Returns an error dictionary with descriptive details.

    Parameters
    ----------
    llm_sql_query : str
        The SQL SELECT query string generated by the LLM.

    Returns
    -------
    dict
        A dictionary with either:
        - "results": a list of JSON records from the executed query.
        - "error": a descriptive message if execution fails.

    Security Considerations
    -----------------------
    - Only SELECT statements are permitted to prevent modification or deletion of data.
    - Should not be used to execute arbitrary SQL from untrusted sources without validation.
    """
    import re
    from connections.Supabase_Connection import create_supabase_connection

    

    # Create Supabase connection
    supabase = create_supabase_connection()

    # Clean query: remove whitespace and trailing semicolons
    llm_sql_query = llm_sql_query.strip().rstrip(";")
   

    try:
        # Execute the query via RPC
        result = supabase.rpc("execute_sql", {"query": llm_sql_query}).execute()

        # Process returned rows into a list of JSON objects
        records = []
        if result.data:
            for row in result.data:
                # Check if row contains 'row_to_json' key
                if isinstance(row, dict) and 'row_to_json' in row:
                    records.append(row['row_to_json'])
                else:
                    # Append row directly if already JSON
                    records.append(row)
        
        return {"results": records}

    except Exception as e:
        # Handle exceptions and return as error dictionary
        print(f"Error details: {str(e)}")
        return {"error": f"Query execution failed: {str(e)}"}